server:
  port: 3344


spring:
  profiles:
    active: @profiles.active@ #读取pom配置
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangbinwen/microservicecloud-config.git
          username: zhangbinwen0705@163.com
          password: binwen19910705
      label: @git.label@
      profile: @profiles.active@

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

